export const returnDonorFakeData = () => {
  return {
    donors: {
      donors: [
        {
          serialNumber: 1,
          donorId: 123,
          donorName: "Maha",
          gender: "Female",
          age: 24,
          bloodGroup: "A+",
          hospitalName: "Apollo Hospital",
          organConsented: "Liver",
          requestNote: "Abcd",
          caseOfficerName: "Franklin Paul",
          caseOfficerPhone: "9737475693",
          donorCaseOfficer: "Mr.Nivin Paul",
          donorCaseOfficerPhone: "8575993394",
          mlcandnonmlc: "Yes",
          causeofDeath: "Accident",
          dateofAccident: "11/03/25",
          dateofAdmission: "12/03/25",
          noofVantilator: "3434",
          apnoeaStatus: "Yes",
          apnoeaDateandTime: "12/03/2025 05:50",
          hospitalType: "Private",
          status: "Ready for review",
        },
        {
          serialNumber: 2,
          donorId: 123,
          donorName: "John",
          gender: "Male",
          age: 30,
          bloodGroup: "O-",
          hospitalName: "Fortis Hospital",
          organConsented: "Kidney",
          requestNote: "Xyz",
          caseOfficerName: "Franklin Paul",
          caseOfficerPhone: "9737475693",
          donorCaseOfficer: "Mr.Nivin Paul",
          donorCaseOfficerPhone: "8575993394",
          mlcandnonmlc: "Yes",
          causeofDeath: "Accident",
          dateofAccident: "11/03/25",
          dateofAdmission: "12/03/25",
          noofVantilator: "3434",
          apnoeaStatus: "Yes",
          apnoeaDateandTime: "12/03/2025 05:50",
          hospitalType: "Private",
          status: "Terminated",
        },
        {
          serialNumber: 3,
          donorId: 123,
          donorName: "Naveen",
          gender: "Male",
          age: 26,
          bloodGroup: "B+",
          hospitalName: "Miot Hospital",
          organConsented: "Heart",
          caseOfficerName: "Franklin Paul",
          caseOfficerPhone: "9737475693",
          donorCaseOfficer: "Mr.Nivin Paul",
          donorCaseOfficerPhone: "8575993394",
          mlcandnonmlc: "Yes",
          causeofDeath: "Accident",
          dateofAccident: "11/03/25",
          dateofAdmission: "12/03/25",
          noofVantilator: "3434",
          apnoeaStatus: "Yes",
          apnoeaDateandTime: "12/03/2025 05:50",
          requestNote: "efg",
          hospitalType: "Private",
          status: "Draft",
        },
      ],
      totalCount: 15,
    },
  };
};
