export const returnTransplantFakeData = () => {
  return {
    liverTransplant: {
      liverTransplant: [
        {
          serialNumber: 1,
          donorHospitalName: "Apollo Hospital",
          donorName: "Maha",
          donorGender: "Female",
          donorBloodGroup: "A+",
          donorAge: "25",
          donorAddress: "Kanagam road iitm",
          recipientName: "Maha",
          recipientGender: "Female",
          recipientBloodGroup: "A+",
          recipientAge: "25",
          recipientAddress: "Kanagam road iitm",
          donorRelationship: "Mother",
          transplantOrgan: "Kidney",
        },
        {
          serialNumber: 2,
          donorHospitalName: "Apollo Hospital",
          donorName: "Naveen",
          donorGender: "Male",
          donorBloodGroup: "B+",
          donorAge: "28",
          donorAddress: "Kanagam road iitm",
          recipientName: "Naveen",
          recipientGender: "Male",
          recipientBloodGroup: "A+",
          recipientAge: "28",
          recipientAddress: "Kanagam road iitm",
          donorRelationship: "Father",
          transplantOrgan: "Heart",
        },
        {
          serialNumber: 3,
          donorHospitalName: "Apollo Hospital",
          donorName: "Venkat",
          donorGender: "Male",
          donorBloodGroup: "O+",
          donorAge: "24",
          donorAddress: "Kanagam road iitm",
          recipientName: "Venkat",
          recipientGender: "Male",
          recipientBloodGroup: "O+",
          recipientAge: "24",
          recipientAddress: "Kanagam road iitm",
          donorRelationship: "Wife",
          transplantOrgan: "Liver",
        },
        {
          serialNumber: 4,
          donorHospitalName: "Apollo Hospital",
          donorName: "Jeffo",
          donorGender: "Female",
          donorBloodGroup: "A+",
          donorAge: "24",
          donorAddress: "Kanagam road iitm",
          recipientName: "Jeffo",
          recipientGender: "Female",
          recipientBloodGroup: "A+",
          recipientAge: "24",
          recipientAddress: "Kanagam road iitm",
          donorRelationship: "Husband",
          transplantOrgan: "Heart",
        },
      ],
      totalCount: 15,
    },
  };
};
