name: CI/CD deployments in Android

on:
  push:
    branches: 
#      - localDev
      # - cloudDev
      - ophub-test
      - uat
      - demo
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonar --info


























    # --------------------------------------------------------------------------------
      # - name: Checkout Repository
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0

      # - name: Set environment variables
      #   id: set_vars
      #   run: |
      #     BRANCH_NAME=${GITHUB_REF##*/}
      #     FLAVOR_NAME=$BRANCH_NAME
      #     BUILD_TYPE="Release"
      #     TODAY=$(date +%F)
      #     # FLAVOR_NAME_LOWER=$(echo "$FLAVOR_NAME" | tr '[:upper:]' '[:lower:]')

      #     echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
      #     echo "flavor_name=$FLAVOR_NAME" >> $GITHUB_ENV
      #     echo "flavor_name_lower=$FLAVOR_NAME_LOWER" >> $GITHUB_ENV
      #     echo "build_type=$BUILD_TYPE" >> $GITHUB_ENV
      #     echo "today_date=$TODAY" >> $GITHUB_ENV

      # - name: Set up Java 17
      #   uses: actions/setup-java@v4.0.0
      #   with:
      #     java-version: '17'
      #     distribution: 'adopt'

      # - name: Set Gradle wrapper executable
      #   run: chmod +x ./gradlew

      # - name: Build APK with Gradle
      #   run: ./gradlew assembleuat${{ env.build_type }}

      # - name: List APK output
      #   run: find app/build/outputs/apk -name "*.apk"

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-south-1

      # - name: Upload APK to S3
      #   run: |
      #     aws s3 cp app/build/outputs/apk/${{ env.flavor_name_lower }}/release/ \
      #       s3://ophub-apk/${{ env.branch_name }}/${{ env.branch_name }}-${{ env.today_date }}/ \
      #       --recursive
