name: CI/CD deployments in Android

on:
  push:
    branches: ["ophub"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.1

      - name: Set up Java 17 (required for Android)
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembledevDebug

      - name: List APK output
        run: find app/build/outputs/apk -name "*.apk"


      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
