name: Deploy React App to IIS (Self-hosted)

on:
  push:
    # branches:
    #   - main

jobs:
  build-and-deploy:
    # runs-on: [self-hosted, windows, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        # uses: kitabisa/sonarqube-action@v1.2.0
        uses: sonarsource/sonarqube-scan-action@master
        with:
          SONAR_HOST_URl: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Create .env.local file
      #   run: |
      #     Set-Content -Path ".env.local" -Value @"
      #     VITE_API_ENDPOINT=$env:REACT_APP_API_URL
      #     # REACT_APP_OTHER=$env:REACT_APP_OTHER
      #     "@
      #   env:
      #     REACT_APP_API_URL: ${{ secrets.VITE_API_ENDPOINT }}
      #     REACT_APP_OTHER: local

      # - name: Install Dependencies
      #   run: npm ci

      # - name: Build React App
      #   run: npm run build

      # - name: Clean IIS Directory
      #   run: |
      #     $path = "C:\inetpub\wwwroot\webapp"
      #     Get-ChildItem -Path $path -Exclude "web.config" -Recurse | Remove-Item -Force -Recurse
         

      # - name: Copy Build to IIS Directory
        # run: Copy-Item -Recurse -Force "dist\*" "C:\inetpub\wwwroot\webapp\"
