name: Deploy React App to IIS (Self-hosted)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows, test]

    env:
      REACT_APP_API_URL: ${{ secrets.VITE_API_ENDPOINT }}
      REACT_APP_ENV: local

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4



      - name: Install Dependencies
        run: npm ci

      - name: Inject .env.production
        run: |
          Set-Content -Path ".env.local" -Value @"
          VITE_API_ENDPOINT=$env:VITE_API_ENDPOINT
          REACT_APP_ENV=$env:REACT_APP_ENV
          "@


      - name: Build React App
        run: npm run build

      - name: Clean IIS Directory
        # run: Remove-Item -Recurse -Force "C:\inetpub\wwwroot\webapp\*"
        run: |
          $path = "C:\inetpub\wwwroot\webapp"
          Get-ChildItem -Path $path -Exclude "web.config" -Recurse | Remove-Item -Force -Recurse
         

      - name: Copy Build to IIS Directory
        run: Copy-Item -Recurse -Force "dist\*" "C:\inetpub\wwwroot\webapp\"
